### ISSUE TITLE
Filtros de estado, cidade e nome não aparecem no mobile

### ISSUE THREAD

**Issue by fm1randa** [leovargasdev/o-meu-voto#4]
## Comportamento Esperado

Os filtros aparecerem no mobile.

## Comportamento Atual

Os filtros somem quando o `width` da tela está em 600 ou abaixo.

## Solução Possível

1. Condicionalmente renderizar o componente de filtros acima da lista dos candidatos quando o _breakpoint_ de 600 for alcançado.
2. Os filtros aparecerem em um Drawer ou Modal ao pressionar um novo botão que seria adicionado à essa tela quando o _breakpoint_  de 600 for alcançado. Exemplo: https://www.pencilandpaper.io/articles/ux-pattern-analysis-mobile-filters#layout-and-positioning-is-key-on-mobile

## Passos para Reproduzir

https://github.com/user-attachments/assets/bdb0ca4e-4036-45bd-918d-089dff7b9047

1. Selecione um estado
3. Selecione uma cidade
4. Diminua a largura da tela para 600 ou menos

**Comment by leovargasdev** [comment]
Olá, subi ontem uma melhoria referente a essa issue [feat: add filter mobile](https://github.com/leovargasdev/o-meu-voto/commit/c0f09e7c11ead107b4158261f9cd54256e233094)

Só usei uma abordagem diferente da sua solução, criei um dropdown que se expande para a tela toda.
